export const specialties = [
    "Behavioral Medicine",
    "Cardiology",
    "Developmental Medicine",
    "Developmental Pediatrics",
    "ENT",
    "Family Medicine",
    "Gastroenterology",
    "Genetics",
    "Genetic Counseling",
    "Internal Medicine",
    "Nephrology",
    "Neurology",
    "Nurse Practitioner",
    "Nutrition",
    "Orthopedics",
    "Pediatric Neurology",
    "Pediatrics",
    "Physician Assistant",
    "Primary Care Physician",
    "Pulmonology",
    "Rehabilitation",
    "Sleep Medicine",
    "Occupational Therapy",
    "Physical Therapy",
    "Speech Therapy",
    "Music Therapy",
    "Other",
  ];

  export const numberTypes = [
    "DEA",
    "ME",
    "NPI"
  ];